### PR TITLE
Installation fix + README additions

### PR DESCRIPTION
**Pull request by cbrxyz**
Hi! This project was really helpful to me, I was looking for something just like this!

However, there was a typo in the installation process, which this PR should fix. I also added some more installation instructions to the introduction for those who may not have installed custom status line components before (aka, me before some googling lol).

Thanks, let me know if you need anything! 😀

### CODE REVIEW

**Comment by EthanG45** [comment]
The `Application Support` folder change is unnecessary I believe. The two folders are symlinked. It also seems to break installation as the script now spits out a cp error.
```
====> 14:29:08 Ethan:INFO : Copy File iTunes.py
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory```

**Comment by EthanG45** [comment]
Thanks for the explanation on using the scripts menu for installing!

**Comment by EthanG45** [comment]
Did you run into similar issues as mentioned here while running the script? https://github.com/danielnehrig/iTerm2segments/issues/3#issuecomment-913044576

**Comment by cbrxyz** [comment]
> The `Application Support` folder change is unnecessary I believe. The two folders are symlinked. It also seems to break installation as the script now spits out a cp error.
> 
> ```
> ====> 14:29:08 Ethan:INFO : Copy File iTunes.py
> usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
>        cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory```
> ```

Hm, that's odd. Do you have both `Application Support` and `ApplicationSupport` under your `~/Library` folder? I only have `~/Library/Application Support` (it has all my application files), `~/Library/ApplicationSupport` was accidentally created by this script so I `rm -rf`'d it.

> Did you run into similar issues as mentioned here while running the script? [#3 (comment)](https://github.com/danielnehrig/iTerm2segments/issues/3#issuecomment-913044576)

Haha, well I actually just checked and that error is there right now! It wasn't there before I read your comment... 👀 It's been working well for about 2 days now, so I'm not sure what caused that.

**Comment by EthanG45** [comment]
Oh dear. I'm fairly certain you just have to properly handle there being a space in the path for the `cp` command. As for the application support folder, the `ApplicationSupport` was created in 2020 and the other in 2015 when this Mac was first booted. So I'm guessing another app is using this and I don't want to break it. 

Edit: it seems iterm made this an option years ago but it's gone now. See here https://discussions.apple.com/thread/251302585

**Comment by EthanG45** [comment]
How's your performance running this? I was getting way too high of CPU usage especially compared to a similar plugin for VSCode. I'm guessing because the AppleScript was being forced to run nearly every second.

**Comment by cbrxyz** [comment]
Ah, right! That should be fixed with that latest commit.

Honestly, no issues with my CPU/memory usage when using this extension vs. not using it. Sorry to hear that the poor performance is happening for you. 😢

**Comment by danielnehrig** [comment]
thanks for the pr i'll test it tomorrow on my macbook

**Pull request merged**
